version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  # Appveyor doesn't get submodules by default.
  - git submodule update --init --recursive
  # Install the haxe chocolatey package (https://chocolatey.org/packages/haxe)
  - cinst haxe --version 3.4.4 -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  # Install project dependencies
  # `> log.txt || type log.txt` is for muting the output unless there is an error
  - haxelib install air3 > log.txt || type log.txt && cmd /C exit 1
  - haxelib list

# We don't use the build section, but do both build and 
# test in `test_script:`.
# It is just because it is more similar to the TravisCI config,
# thus it would be easier to update both of them.
build: off

test_script:
  - haxe Swivel.hxml
